const parameters = {
              "steps": [
                  {
                  "title": "Question Answers Submitted Crud",
                  "parameters": {
                      "fields": [
                      {
                          "name": "question_answers_submitted",
                          "type": "section",
                          "title": "Question Answers Submitted CRUD",
                          "hideInCreateForm": false,
                          "visible": false, 
                          "required": false,
                          "disabled": false,
                          "validations": "",
                          "dependancyCheck": false,
                          "isPrefilled": false,
                          "source": "req.body",
                          "title": "Question_answers_submitted",
                          "childFields": [
                                {
                                  "name": "questionAnswersSubmitted_id",
                                  "label": "id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": true,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.query",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "questionAnswersSubmitted_id"
                                },
                               {
                                  "name": "actionPerformerURDD",
                                  "label": "actionPerformerURDD",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "actionPerformerURDD",
                                  "alias" : "actionPerformerURDD",
                                },
                              
                                  {
                                  "name": "urdd",
                                  "label": "Urdd",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "questionAnswersSubmitted_urdd",
                                  "alias" : "question_answers_submitted.urdd",
                                  },
                                  {
                                  "name": "question_id",
                                  "label": "Question Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "questionAnswersSubmitted_questionId",
                                  "alias" : "question_answers_submitted.question_id",
                                  },
                                  {
                                  "name": "questions_solution_options_id",
                                  "label": "Questions Solution Options Id",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "questionAnswersSubmitted_questionsSolutionOptionsId",
                                  "alias" : "question_answers_submitted.questions_solution_options_id",
                                  },
                                  {
                                  "name": "description",
                                  "label": "Description",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "questionAnswersSubmitted_description",
                                  "alias" : "question_answers_submitted.description",
                                  },
                                  {
                                  "name": "marks_obtained",
                                  "label": "Marks Obtained",
                                  "title": "",
                                  "type": "textField",
                                  "required": false,
                                  "hideInCreateForm": false,
                                  "visible": true,
                                  "disabled": false,
                                  "dependancyCheck": false,
                                  "isPrefilled": false,
                                  "source": "req.body",
                                  "min": "",
                                  "max": "",
                                  "selectServer": false,
                                  "dynamicKey": "questionAnswersSubmitted_marksObtained",
                                  "alias" : "question_answers_submitted.marks_obtained",
                                  },
                                  
                          ]
                      }
                      ]
                  },
                  "buttons": [
                      {
                      "type": "submit",
                      "label": "Submit"
                      }
                  ]
                  }
              ],
              "colMapper": "{ 'question_answers_submitted_questionAnswersSubmittedId' : 'question_answers_submitted_id',  'question_answers_submitted_urdd' : 'urdd',  'question_answers_submitted_questionId' : 'question_id',  'question_answers_submitted_questionsSolutionOptionsId' : 'questions_solution_options_id',  'question_answers_submitted_description' : 'description',  'question_answers_submitted_marksObtained' : 'marks_obtained'}"
              };
              module.exports = parameters;